In [2]:
# Ensure compatibility
from __future__ import absolute_import, division, print_function

# Import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Import TensorFlow and Keras packages
import tensorflow as tf
from tensorflow import keras

print(tf.__version__)

2.16.1

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load and prepare the training data
df_train = pd.read_csv('option_train.csv')
X = df_train.iloc[:, 1:].drop(columns=['Value', 'BS'])
y = df_train['BS']

# Split the data into a training set and a validation set
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the RandomForest model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model on the training subset
model.fit(X_train, y_train)

# Predict on the validation subset
val_predictions = model.predict(X_val)

# Calculate the classification error
classification_error = 1 - accuracy_score(y_val, val_predictions)
print(f"Classification Error on Validation Set: {classification_error}")

# Re-train the model on the entire training dataset
model.fit(X, y)

# Load the test dataset
df_test = pd.read_csv('option_test_nolabel.csv')
X_test = df_test.iloc[:, 1:]

# Predict on the test dataset
test_predictions = model.predict(X_test)
test_predictions_binary = [1 if i == 'Over' else 0 for i in test_predictions]

# Save the predictions to a CSV file
predictions_df = pd.DataFrame(test_predictions_binary, columns=['BS'])
predictions_df.to_csv('prediction_file.csv', index=False)

print("Predictions saved to prediction_file.csv")

Classification Error on Validation Set: 0.06699999999999995
Predictions saved to prediction_file.csv

In [11]:
x = pd.read_csv('prediction_file.csv')
x

     BS
0     0
1     0
2     0
3     0
4     0
..   ..
495   0
496   1
497   0
498   0
499   0

[500 rows x 1 columns]

In [12]:
x.to_clipboard(index = False)

In [6]:
pd.read_csv('group_0_prediction.csv')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Value,BS,NaN,NaN,NaN,NaN,NaN
1,1,0,NaN,NaN,NaN,NaN,NaN
2,2,0,NaN,NaN,NaN,NaN,NaN
3,1,0,NaN,NaN,NaN,NaN,NaN
4,1,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
496,1,0,NaN,NaN,NaN,NaN,NaN
497,1,0,NaN,NaN,NaN,NaN,NaN
498,1,0,NaN,NaN,NaN,NaN,NaN
499,1,0,NaN,NaN,NaN,NaN,NaN
500,2,1,NaN,NaN,NaN,NaN,NaN